### PR TITLE
Added implicit grant

### PR DESCRIPTION
**Pull request by KodingDev**
Hello!

I've implemented the option for the implicit grant flow as an additional login method.
In my testing it is working well, however any feedback is welcome and appreciated.

### CODE REVIEW

**Comment by okrad** [comment]
Hi @KodingDev, thank you for the pull request!

Given that the implicit flow is [strongly discouraged](https://oauth.net/2/grant-types/implicit/) nowaday, I was wondering what your usage scenario is. Do you need to interact with a "legacy" application? 

Also, the implicit flow is normally used in web applications, but oauth2_client doesn't currently support the web platform...

**Comment by KodingDev** [comment]
Hi!

I integrated this into my own fork initially to support an app called AniList so I don't need to redistribute the client secret.
I understand it's legacy, but having the option there isn't too bad as long as it's properly stated that you shouldn't use it unless necessary.
From what I saw recommended by AniList, it's the best option for my use case since they don't currently support PKCE.

I appreciate the response though!

**Comment by okrad** [comment]
Hi, 
the PKCE extension can be disabled with `enablePKCE: false`, both in the client's `getTokenWithAuthCodeFlow` and (since the latest version) in the OAuth2Helper (see #35).

Anyway I agree with you that it won't be too bad to have the option, so I'll merge your PR. I just need to find the time to write down some test cases...

**Comment by KodingDev** [comment]
Hey again,

PKCE doesn't cause an issue with this, it works just fine when enabled. 
Main thing is I don't want to supply the client secret which (in my research) is solved through PKCE, however the application doesn't support it.

I appreciate your feedback though, thanks for being willing to merge regardless!

**Pull request merged**
