### PR TITLE
update dependencies in pubspec.yaml

### PR DESCRIPTION
**Pull request by Menelphor**

### CODE REVIEW

**Comment by jheld** [comment]
@teranetsrl can you review this?

**Comment by okrad** [comment]
Hi @Menelphor, 
looks good to me and all unit tests are passing, but since many dependencies upgraded their major version, I'm afraid they'll turn out to be somehow incompatible. Did you test it on a real project?

**Comment by Menelphor** [comment]
@okrad sorry christmas holidays kind interrupted my workflow.

I did and additionally I did push some changes:
I updated the dart sdk to 2.14 which lead to a linter issue, which i also fixed.

**Comment by okrad** [comment]
Hi @Menelphor, merge done, thank you!

**Pull request merged**
